name: Native Build

defaults:
  run:
    working-directory: packages/native

on:
  push:
    branches:
      - main
    paths:
      - "packages/native/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/native/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: packages/native/yarn.lock
      - name: Install dependencies
        run: yarn install --focus
      - name: Linter
        run: yarn lint
      - name: Typecheck
        run: yarn typecheck
